const productos = [
    {
        id: 1,
        nombre: "Slam Dunk 01",
        precio: 8000,
        tipo: "manga",
        genero: "deportes",
        imagen: "./resources/images/slam-dunk-01.jpg",
        stock: true,
    },
    {
        id: 2,
        nombre: "Tokyo Ghoul 01",
        precio: 6500,
        tipo: "manga",
        genero: "fantasia",
        imagen: "./resources/images/tokyo-ghoul-01.jpg",
        stock: true,
    },
    {
        id: 3,
        nombre: "The Amazing Spider Man 01",
        precio: 12000,
        tipo: "comic",
        genero: "superheroe",
        imagen: "./resources/images/amazing-spider-man-01.jpg",
        stock: true,
    },
    {
        id: 4,
        nombre: "Batman: Los pecados del padre",
        precio: 20000,
        tipo: "comic",
        genero: "superheroe",
        imagen: "./resources/images/batman-pecados-padre.jpg",
        stock: true,
    },
    {
        id: 5,
        nombre: "Saint Seiya 01",
        precio: 15000,
        tipo: "manga",
        genero: "artes marciales",
        imagen: "./resources/images/saint-seiya-01.jpg",
        stock: true,
    },
    {
        id: 6,
        nombre: "Monster 01",
        precio: 15000,
        tipo: "manga",
        genero: "suspenso",
        imagen: "./resources/images/monster-01.jpg",
        stock: true,
    },
    {
        id: 7,
        nombre: "Rurouni Kenshin 01",
        precio: 15000,
        tipo: "manga",
        genero: "accion",
        imagen: "./resources/images/rurouni-kenshin-01.jpg",
        stock: true,
    },
    {
        id: 8,
        nombre: "Superman: Muerte - 30 aniversario",
        precio: 30000,
        tipo: "comic",
        genero: "superheroe",
        imagen: "./resources/images/superman-muerte-aniversario.jpg",
        stock: true,
    },
    {
        id: 9,
        nombre: "X-MEN 01",
        precio: 12000,
        tipo: "comic",
        genero: "accion",
        imagen: "./resources/images/x-men-01.jpg",
        stock: true,
    },
    {
        id: 10,
        nombre: "Captain Tsubasa 01",
        precio: 15000,
        tipo: "manga",
        genero: "deportes",
        imagen: "./resources/images/captain-tsubasa-01.jpg",
        stock: true,
    },
    {
        id: 11,
        nombre: "Blame! 01",
        precio: 18000,
        tipo: "manga",
        genero: "ciencia ficcion",
        imagen: "./resources/images/blame-01.jpg",
        stock: true,
    },
    {
        id: 12,
        nombre: "Watchmen",
        precio: 30000,
        tipo: "comic",
        genero: "superheroes",
        imagen: "./resources/images/watchmen.jpg",
        stock: true,
    },
]